# Generated by Django 4.0 on 2022-04-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ctreated_on',
            new_name='created_on',
        ),
    ]
